# Generated by Django 3.0.6 on 2020-06-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0002_auto_20200605_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='red_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
