# Generated by Django 3.0.6 on 2020-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'shipping')], max_length=1),
        ),
    ]
