# Generated by Django 3.0.6 on 2020-06-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0007_searchterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryn', models.CharField(choices=[('Shirt', 'Shirt'), ('Sport wear', 'Sport wear'), ('Outwear', 'Outwear')], max_length=17)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='SearchTerm',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(to='stor.Category'),
        ),
    ]
