# Generated by Django 3.0.6 on 2020-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0009_auto_20200614_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryn',
            field=models.CharField(choices=[('man', 'man'), ('women', 'women'), ('chiled', 'chiled'), ('choese', 'choese'), ('sport', 'sport'), ('dress', 'dress')], max_length=17),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
