# Generated by Django 3.0.6 on 2020-06-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0010_auto_20200614_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('categoryn',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('title',), 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stor.Category'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories to which this item belongs.', to='stor.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
