# Generated by Django 3.0.6 on 2020-06-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0012_auto_20200614_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryn',
            field=models.CharField(max_length=17),
        ),
    ]
