# Generated by Django 3.0.6 on 2020-06-15 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0013_auto_20200614_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryn',
            field=models.CharField(choices=[('man', 'man'), ('women', 'women'), ('chiled', 'chiled'), ('choese', 'choese'), ('sport', 'sport'), ('dress', 'dress')], max_length=17),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stor.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
    ]
