# Generated by Django 3.0.6 on 2020-06-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0017_auto_20200615_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tag',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stor.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stor.Category'),
        ),
    ]
