# Generated by Django 3.0.6 on 2020-06-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0021_categorymanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryn',
            field=models.CharField(choices=[('man', 'man'), ('women', 'women'), ('chiled', 'chiled'), ('sport', 'sport')], max_length=17),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
