# Generated by Django 3.0.6 on 2020-06-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0022_auto_20200615_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryManager',
        ),
    ]
