# Generated by Django 3.0.6 on 2020-06-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0023_delete_categorymanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('adver', models.CharField(max_length=15)),
            ],
        ),
    ]
