# Generated by Django 3.0.6 on 2020-06-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0024_slides_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slides_image',
            new_name='Slidesimage',
        ),
    ]
