# Generated by Django 3.0.6 on 2020-06-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0025_auto_20200615_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='adver',
            field=models.CharField(default='text', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
