# Generated by Django 3.0.6 on 2020-06-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0026_auto_20200615_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Slidesimage',
        ),
        migrations.RemoveField(
            model_name='category',
            name='adver',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
